
[theme]
# Primary accent color (Rose Pink)
primaryColor = "#E08396"

# Background color (Linen)
backgroundColor = "#FAF0E6"

# Sidebar and Widget background (Sage)
secondaryBackgroundColor = "#DCE0B8"

# Text color (Dark Brown)
textColor = "#5D4037"

# font 
font = "sans serif"

# border color (Rose pink)
borderColor = ""#E08396"
